/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Gilson Efren Cruz Yagual
 */
public class Inventario extends javax.swing.JFrame {

   private ImageIcon imagen;
   private Icon icono;
   private ImageIcon imagenLupa;
   private Icon iconoLupa;
    
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.ajustarImagen(lblLogoEcuaStock,"src/main/java/picture/logoEcuastock.png");
        this.ajustarImagenBtn(btnBuscarActualizar, "src/main/java/picture/lupa.png");
        
        
//        jdcFechaIngresoRegistros.setMinSelectableDate(new date());
//        jdcFechaIngresoRegistros.setMaxSelectableDate(new date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckModuloInv = new javax.swing.JPanel();
        lblLogoEcuaStock = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblNombreSucursal = new javax.swing.JLabel();
        jtpInventario = new javax.swing.JTabbedPane();
        pnlConsultar = new javax.swing.JPanel();
        btnOkConsultar = new javax.swing.JButton();
        btnCancelarConsultar = new javax.swing.JButton();
        lblCodigoConsultar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultar = new javax.swing.JTable();
        txtCodigoConsulta = new javax.swing.JTextField();
        lblEanConsultar = new javax.swing.JLabel();
        tctEanConsulta = new javax.swing.JTextField();
        lblDescripcionConsultar = new javax.swing.JLabel();
        txtDescripcionConsultar = new javax.swing.JTextField();
        lblFechaInicioConsultar = new javax.swing.JLabel();
        lblFechaFinConsultar = new javax.swing.JLabel();
        jcbBuscarPorConsultar = new javax.swing.JComboBox<>();
        lblBuscarPorConsultar = new javax.swing.JLabel();
        lblModuloConsultar = new javax.swing.JLabel();
        pnlRegistros = new javax.swing.JPanel();
        lblCodigoRegistros = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtRegistros = new javax.swing.JTable();
        lblFechaIngresoRegistros = new javax.swing.JLabel();
        lblEanRegistros = new javax.swing.JLabel();
        lblCantidadRegistros = new javax.swing.JLabel();
        btnOkRegistros = new javax.swing.JButton();
        btnCancelarRegistros = new javax.swing.JButton();
        lblDescripcionRegistros = new javax.swing.JLabel();
        lblCategoriaRegistros = new javax.swing.JLabel();
        txtCategoriaRegistros = new javax.swing.JTextField();
        txtCodigoRegistros = new javax.swing.JTextField();
        txtCantidadRegistros = new javax.swing.JTextField();
        txtDescripcionRegistros = new javax.swing.JTextField();
        txtEanRegistros = new javax.swing.JTextField();
        lblModuloRegistros = new javax.swing.JLabel();
        pnlActualizar = new javax.swing.JPanel();
        lblCodigoActualizar = new javax.swing.JLabel();
        lblDescripcionActualizar = new javax.swing.JLabel();
        lblEanActualizar = new javax.swing.JLabel();
        lblCategoriaActualizar = new javax.swing.JLabel();
        lblCantidadActualActualizar = new javax.swing.JLabel();
        lblCantidadReconteoActualizar = new javax.swing.JLabel();
        btnGuardarActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtActualizar = new javax.swing.JTable();
        btnBuscarActualizar = new javax.swing.JButton();
        btnModificarActualizar = new javax.swing.JButton();
        btnCancelarActualizar = new javax.swing.JButton();
        txtCodigoActualizar = new javax.swing.JTextField();
        txtCodigoActualizar1 = new javax.swing.JTextField();
        txtCodigoActualizar2 = new javax.swing.JTextField();
        txtCodigoActualizar3 = new javax.swing.JTextField();
        txtCodigoActualizar4 = new javax.swing.JTextField();
        txtCodigoActualizar5 = new javax.swing.JTextField();
        lblModuloRegistros1 = new javax.swing.JLabel();
        lblModuloRegistros2 = new javax.swing.JLabel();
        lblModuloActualizar = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bckModuloInv.setBackground(new java.awt.Color(255, 255, 255));
        bckModuloInv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bckModuloInv.add(lblLogoEcuaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 120, 80));

        pnlBotones.setBackground(new java.awt.Color(0, 153, 255));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Registros");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnActualizar1.setText("REGRESAR");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnConsultar)
                .addGap(54, 54, 54)
                .addComponent(btnIngresar)
                .addGap(46, 46, 46)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        bckModuloInv.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        pnlDatos.setBackground(new java.awt.Color(51, 51, 255));

        lblNombreSucursal.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lblNombreSucursal.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreSucursal.setText("SUCURSAL NORTE");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(lblNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bckModuloInv.add(pnlDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 820, 90));

        btnOkConsultar.setText("OK");
        btnOkConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkConsultarActionPerformed(evt);
            }
        });

        btnCancelarConsultar.setText("Cancelar");

        lblCodigoConsultar.setText("Codigo");

        jtConsultar.setForeground(new java.awt.Color(0, 255, 255));
        jtConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FECHA INGRESO", "FECHA SALIDA", "EAN", "CODIGO", "DESCRIPCION", "CATEGORIA"
            }
        ));
        jScrollPane1.setViewportView(jtConsultar);
        if (jtConsultar.getColumnModel().getColumnCount() > 0) {
            jtConsultar.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtConsultar.getColumnModel().getColumn(1).setPreferredWidth(10);
            jtConsultar.getColumnModel().getColumn(2).setPreferredWidth(40);
            jtConsultar.getColumnModel().getColumn(3).setPreferredWidth(60);
            jtConsultar.getColumnModel().getColumn(4).setPreferredWidth(150);
            jtConsultar.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        lblEanConsultar.setText("Ean");

        tctEanConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tctEanConsultaActionPerformed(evt);
            }
        });

        lblDescripcionConsultar.setText("Descripcion");

        txtDescripcionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionConsultarActionPerformed(evt);
            }
        });

        lblFechaInicioConsultar.setText("Fecha Inicio");

        lblFechaFinConsultar.setText("Fecha Fin");

        jcbBuscarPorConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Producto", "Categoria", "Fecha", " " }));
        jcbBuscarPorConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBuscarPorConsultarActionPerformed(evt);
            }
        });

        lblBuscarPorConsultar.setText("Buscar por");

        lblModuloConsultar.setText("MODULO CONSULTAR");

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addComponent(lblModuloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addComponent(lblCodigoConsultar)
                                .addGap(8, 8, 8)
                                .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblDescripcionConsultar))
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addComponent(lblEanConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(tctEanConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaInicioConsultar)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaFinConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addComponent(txtDescripcionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBuscarPorConsultar)))
                        .addGap(41, 41, 41)
                        .addComponent(jcbBuscarPorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarLayout.createSequentialGroup()
                                .addComponent(btnCancelarConsultar)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarLayout.createSequentialGroup()
                                .addComponent(btnOkConsultar)
                                .addGap(23, 23, 23))))))
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoConsultar)
                    .addComponent(txtCodigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkConsultar)
                    .addComponent(lblDescripcionConsultar)
                    .addComponent(txtDescripcionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBuscarPorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarPorConsultar))
                .addGap(17, 17, 17)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tctEanConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaInicioConsultar)
                        .addComponent(lblEanConsultar))
                    .addComponent(lblFechaFinConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModuloConsultar)
                .addGap(21, 21, 21))
        );

        jtpInventario.addTab("tab1", pnlConsultar);

        lblCodigoRegistros.setText("Codigo");

        jtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EAN", "CODIGO", "DESCRIPCION", "CATEGORIA", "FECHA DE INGRESO", "CANTIDAD"
            }
        ));
        jScrollPane3.setViewportView(jtRegistros);
        if (jtRegistros.getColumnModel().getColumnCount() > 0) {
            jtRegistros.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtRegistros.getColumnModel().getColumn(1).setPreferredWidth(40);
            jtRegistros.getColumnModel().getColumn(2).setPreferredWidth(200);
            jtRegistros.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtRegistros.getColumnModel().getColumn(4).setPreferredWidth(30);
            jtRegistros.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        lblFechaIngresoRegistros.setText("Fecha de Ingreso");

        lblEanRegistros.setText("EAN");

        lblCantidadRegistros.setText("Cantidad");

        btnOkRegistros.setText("OK");
        btnOkRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkRegistrosActionPerformed(evt);
            }
        });

        btnCancelarRegistros.setText("Cancelar");

        lblDescripcionRegistros.setText("Descripcion");

        lblCategoriaRegistros.setText("Categoria");

        txtCategoriaRegistros.setEditable(false);

        txtDescripcionRegistros.setEditable(false);
        txtDescripcionRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionRegistrosActionPerformed(evt);
            }
        });

        txtEanRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanRegistrosActionPerformed(evt);
            }
        });

        lblModuloRegistros.setText("MODULO REGISTROS");

        javax.swing.GroupLayout pnlRegistrosLayout = new javax.swing.GroupLayout(pnlRegistros);
        pnlRegistros.setLayout(pnlRegistrosLayout);
        pnlRegistrosLayout.setHorizontalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoRegistros)
                            .addComponent(lblEanRegistros))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEanRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblDescripcionRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcionRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblFechaIngresoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblCantidadRegistros)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblCategoriaRegistros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCategoriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(btnOkRegistros)
                                .addGap(20, 20, 20))
                            .addComponent(btnCancelarRegistros, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblModuloRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        pnlRegistrosLayout.setVerticalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(btnOkRegistros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarRegistros)
                            .addComponent(txtCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoRegistros)
                            .addComponent(lblDescripcionRegistros)
                            .addComponent(lblCategoriaRegistros)
                            .addComponent(txtCategoriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEanRegistros)
                                .addComponent(txtEanRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCantidadRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaIngresoRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModuloRegistros)
                .addGap(11, 11, 11))
        );

        jtpInventario.addTab("tab2", pnlRegistros);

        lblCodigoActualizar.setText("Codigo");

        lblDescripcionActualizar.setText("Descripcion");

        lblEanActualizar.setText("Ean");

        lblCategoriaActualizar.setText("Categoria");

        lblCantidadActualActualizar.setText("Cantidad Actual");

        lblCantidadReconteoActualizar.setText("Cantidad Reconteo");

        btnGuardarActualizar.setText("Guardar");
        btnGuardarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActualizarActionPerformed(evt);
            }
        });

        jtActualizar.setForeground(new java.awt.Color(0, 204, 204));
        jtActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EAN", "CODIGO", "DESCRIPCION", "FECHA ", "CANTIDAD ACTUAL", "RECONTEO"
            }
        ));
        jScrollPane2.setViewportView(jtActualizar);
        if (jtActualizar.getColumnModel().getColumnCount() > 0) {
            jtActualizar.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtActualizar.getColumnModel().getColumn(1).setPreferredWidth(30);
            jtActualizar.getColumnModel().getColumn(2).setPreferredWidth(150);
            jtActualizar.getColumnModel().getColumn(3).setPreferredWidth(30);
            jtActualizar.getColumnModel().getColumn(4).setPreferredWidth(30);
            jtActualizar.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        btnBuscarActualizar.setBorder(null);
        btnBuscarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActualizarActionPerformed(evt);
            }
        });

        btnModificarActualizar.setText("Modificar");
        btnModificarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActualizarActionPerformed(evt);
            }
        });

        btnCancelarActualizar.setText("Cancelar");
        btnCancelarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarActionPerformed(evt);
            }
        });

        txtCodigoActualizar1.setEditable(false);

        txtCodigoActualizar5.setEditable(false);

        lblModuloRegistros1.setText("Modulo Registros");

        lblModuloRegistros2.setText("Modulo Registros");

        lblModuloActualizar.setText("MODULO ACTUALIZAR");

        javax.swing.GroupLayout pnlActualizarLayout = new javax.swing.GroupLayout(pnlActualizar);
        pnlActualizar.setLayout(pnlActualizarLayout);
        pnlActualizarLayout.setHorizontalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblEanActualizar)
                                .addGap(24, 24, 24)
                                .addComponent(txtCodigoActualizar))
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblCodigoActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addComponent(lblDescripcionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(txtCodigoActualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblCategoriaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarActualizar)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblCantidadActualActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCantidadReconteoActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoActualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnGuardarActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarActualizar)
                                .addGap(10, 10, 10))))
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addComponent(lblModuloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlActualizarLayout.createSequentialGroup()
                    .addGap(338, 338, 338)
                    .addComponent(lblModuloRegistros1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                    .addContainerGap(348, Short.MAX_VALUE)
                    .addComponent(lblModuloRegistros2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(329, 329, 329)))
        );
        pnlActualizarLayout.setVerticalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoActualizar)
                        .addComponent(lblCategoriaActualizar)
                        .addComponent(lblDescripcionActualizar)
                        .addComponent(btnModificarActualizar)
                        .addComponent(txtCodigoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoActualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEanActualizar)
                    .addComponent(lblCantidadActualActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCantidadReconteoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarActualizar)
                    .addComponent(btnCancelarActualizar)
                    .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoActualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoActualizar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModuloActualizar)
                .addGap(50, 50, 50))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlActualizarLayout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(lblModuloRegistros1)
                    .addContainerGap(215, Short.MAX_VALUE)))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                    .addContainerGap(225, Short.MAX_VALUE)
                    .addComponent(lblModuloRegistros2)
                    .addGap(205, 205, 205)))
        );

        jtpInventario.addTab("tab3", pnlActualizar);

        bckModuloInv.add(jtpInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 820, 440));

        lblNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 51, 255));
        lblNombreUsuario.setText("BIENVENIDO USUARIO JCPALMER");
        bckModuloInv.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bckModuloInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bckModuloInv, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new MenuPrincipal().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new MenuPrincipal().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new MenuPrincipal().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new MenuPrincipal().setVisible(true);
            }
        });*/
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        jtpInventario.setSelectedIndex(2);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtDescripcionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionConsultarActionPerformed

    private void tctEanConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tctEanConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tctEanConsultaActionPerformed

    private void btnOkConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkConsultarActionPerformed

    private void jcbBuscarPorConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBuscarPorConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBuscarPorConsultarActionPerformed

    private void btnOkRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkRegistrosActionPerformed

    private void txtEanRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanRegistrosActionPerformed

    private void txtDescripcionRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionRegistrosActionPerformed

    private void btnGuardarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActualizarActionPerformed

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    private void btnModificarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActualizarActionPerformed

    private void btnCancelarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
     
        jtpInventario.setSelectedIndex(0);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        jtpInventario.setSelectedIndex(1);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnCancelarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    private void ajustarImagen(JLabel lbl,String ruta )
    {
        this.imagen= new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(),
                lbl.getHeight(),
                Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    private void ajustarImagenBtn(JButton btn,String ruta )
    {
        this.imagenLupa= new ImageIcon(ruta);
        this.iconoLupa = new ImageIcon(this.imagenLupa.getImage().getScaledInstance(
                btn.getWidth(),
                btn.getHeight(),
                Image.SCALE_DEFAULT)
        );
        btn.setIcon(this.iconoLupa);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bckModuloInv;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JButton btnCancelarActualizar;
    private javax.swing.JButton btnCancelarConsultar;
    private javax.swing.JButton btnCancelarRegistros;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardarActualizar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificarActualizar;
    private javax.swing.JButton btnOkConsultar;
    private javax.swing.JButton btnOkRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbBuscarPorConsultar;
    private javax.swing.JTable jtActualizar;
    private javax.swing.JTable jtConsultar;
    private javax.swing.JTable jtRegistros;
    private javax.swing.JTabbedPane jtpInventario;
    private javax.swing.JLabel lblBuscarPorConsultar;
    private javax.swing.JLabel lblCantidadActualActualizar;
    private javax.swing.JLabel lblCantidadReconteoActualizar;
    private javax.swing.JLabel lblCantidadRegistros;
    private javax.swing.JLabel lblCategoriaActualizar;
    private javax.swing.JLabel lblCategoriaRegistros;
    private javax.swing.JLabel lblCodigoActualizar;
    private javax.swing.JLabel lblCodigoConsultar;
    private javax.swing.JLabel lblCodigoRegistros;
    private javax.swing.JLabel lblDescripcionActualizar;
    private javax.swing.JLabel lblDescripcionConsultar;
    private javax.swing.JLabel lblDescripcionRegistros;
    private javax.swing.JLabel lblEanActualizar;
    private javax.swing.JLabel lblEanConsultar;
    private javax.swing.JLabel lblEanRegistros;
    private javax.swing.JLabel lblFechaFinConsultar;
    private javax.swing.JLabel lblFechaIngresoRegistros;
    private javax.swing.JLabel lblFechaInicioConsultar;
    private javax.swing.JLabel lblLogoEcuaStock;
    private javax.swing.JLabel lblModuloActualizar;
    private javax.swing.JLabel lblModuloConsultar;
    private javax.swing.JLabel lblModuloRegistros;
    private javax.swing.JLabel lblModuloRegistros1;
    private javax.swing.JLabel lblModuloRegistros2;
    private javax.swing.JLabel lblNombreSucursal;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlActualizar;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlRegistros;
    private javax.swing.JTextField tctEanConsulta;
    private javax.swing.JTextField txtCantidadRegistros;
    private javax.swing.JTextField txtCategoriaRegistros;
    private javax.swing.JTextField txtCodigoActualizar;
    private javax.swing.JTextField txtCodigoActualizar1;
    private javax.swing.JTextField txtCodigoActualizar2;
    private javax.swing.JTextField txtCodigoActualizar3;
    private javax.swing.JTextField txtCodigoActualizar4;
    private javax.swing.JTextField txtCodigoActualizar5;
    private javax.swing.JTextField txtCodigoConsulta;
    private javax.swing.JTextField txtCodigoRegistros;
    private javax.swing.JTextField txtDescripcionConsultar;
    private javax.swing.JTextField txtDescripcionRegistros;
    private javax.swing.JTextField txtEanRegistros;
    // End of variables declaration//GEN-END:variables
}
