/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author Erick Contreras
 */
public class Registros extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckModuloInv = new javax.swing.JPanel();
        lblLogoEcuaStock = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnActualizar1 = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblNombreSucursal = new javax.swing.JLabel();
        jtpInventario = new javax.swing.JTabbedPane();
        pnlConsultar = new javax.swing.JPanel();
        btnOkConsultar = new javax.swing.JButton();
        btnCancelarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultar = new javax.swing.JTable();
        lblEanConsultar = new javax.swing.JLabel();
        lblFechaInicioConsultar = new javax.swing.JLabel();
        lblFechaFinConsultar = new javax.swing.JLabel();
        lblBuscarPorConsultar = new javax.swing.JLabel();
        lblModuloConsultar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        pnlRegistros = new javax.swing.JPanel();
        lblCodigoRegistros = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtRegistros = new javax.swing.JTable();
        lblFechaIngresoRegistros = new javax.swing.JLabel();
        lblEanRegistros = new javax.swing.JLabel();
        lblCantidadRegistros = new javax.swing.JLabel();
        btnOkRegistros = new javax.swing.JButton();
        btnCancelarRegistros = new javax.swing.JButton();
        lblDescripcionRegistros = new javax.swing.JLabel();
        lblCategoriaRegistros = new javax.swing.JLabel();
        txtCategoriaRegistros = new javax.swing.JTextField();
        txtCodigoRegistros = new javax.swing.JTextField();
        txtCantidadRegistros = new javax.swing.JTextField();
        txtDescripcionRegistros = new javax.swing.JTextField();
        txtEanRegistros = new javax.swing.JTextField();
        lblModuloRegistros = new javax.swing.JLabel();
        pnlActualizar = new javax.swing.JPanel();
        lblCodigoActualizar = new javax.swing.JLabel();
        lblDescripcionActualizar = new javax.swing.JLabel();
        lblEanActualizar = new javax.swing.JLabel();
        lblCategoriaActualizar = new javax.swing.JLabel();
        lblCantidadActualActualizar = new javax.swing.JLabel();
        lblCantidadReconteoActualizar = new javax.swing.JLabel();
        btnGuardarActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtActualizar = new javax.swing.JTable();
        btnBuscarActualizar = new javax.swing.JButton();
        btnModificarActualizar = new javax.swing.JButton();
        btnCancelarActualizar = new javax.swing.JButton();
        txtCodigoActualizar = new javax.swing.JTextField();
        txtCodigoActualizar1 = new javax.swing.JTextField();
        txtCodigoActualizar2 = new javax.swing.JTextField();
        txtCodigoActualizar3 = new javax.swing.JTextField();
        txtCodigoActualizar4 = new javax.swing.JTextField();
        txtCodigoActualizar5 = new javax.swing.JTextField();
        lblModuloRegistros1 = new javax.swing.JLabel();
        lblModuloRegistros2 = new javax.swing.JLabel();
        lblModuloActualizar = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bckModuloInv.setBackground(new java.awt.Color(255, 255, 255));
        bckModuloInv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bckModuloInv.add(lblLogoEcuaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 120, 80));

        pnlBotones.setBackground(new java.awt.Color(0, 153, 255));

        btnActualizar1.setText("REGRESAR");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        bckModuloInv.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        pnlDatos.setBackground(new java.awt.Color(51, 51, 255));

        lblNombreSucursal.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lblNombreSucursal.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreSucursal.setText("SUCURSAL NORTE");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(lblNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bckModuloInv.add(pnlDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 820, 90));

        btnOkConsultar.setText("OK");
        btnOkConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkConsultarActionPerformed(evt);
            }
        });

        btnCancelarConsultar.setText("Cancelar");

        jtConsultar.setForeground(new java.awt.Color(0, 255, 255));
        jtConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FECHA INGRESO", "FECHA SALIDA", "EAN", "CODIGO", "DESCRIPCION", "CATEGORIA"
            }
        ));
        jScrollPane1.setViewportView(jtConsultar);

        lblEanConsultar.setText("Categoria");

        lblFechaInicioConsultar.setText("Fecha Entrada");

        lblFechaFinConsultar.setText("Fecha Salida");

        lblBuscarPorConsultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscarPorConsultar.setText("Buscar por");

        lblModuloConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModuloConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModuloConsultar.setText("REPORTES");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría..." }));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("DESCARGAR REPORTE");

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                                        .addComponent(lblEanConsultar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblFechaInicioConsultar)
                                        .addGap(157, 157, 157)
                                        .addComponent(lblFechaFinConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(179, 179, 179))
                                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                                        .addComponent(lblBuscarPorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(185, 185, 185)))
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelarConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnOkConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlConsultarLayout.createSequentialGroup()
                                .addComponent(lblModuloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(22, 22, 22)))
                        .addContainerGap())))
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnOkConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarConsultar))
                    .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlConsultarLayout.createSequentialGroup()
                            .addComponent(lblBuscarPorConsultar)
                            .addGap(18, 18, 18)
                            .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFechaInicioConsultar)
                                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEanConsultar)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(2, 2, 2))
                        .addComponent(lblFechaFinConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModuloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59))
        );

        jtpInventario.addTab("tab1", pnlConsultar);

        lblCodigoRegistros.setText("Codigo");

        jtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EAN", "CODIGO", "DESCRIPCION", "CATEGORIA", "FECHA DE INGRESO", "CANTIDAD"
            }
        ));
        jScrollPane3.setViewportView(jtRegistros);

        lblFechaIngresoRegistros.setText("Fecha de Ingreso");

        lblEanRegistros.setText("EAN");

        lblCantidadRegistros.setText("Cantidad");

        btnOkRegistros.setText("OK");
        btnOkRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkRegistrosActionPerformed(evt);
            }
        });

        btnCancelarRegistros.setText("Cancelar");

        lblDescripcionRegistros.setText("Descripcion");

        lblCategoriaRegistros.setText("Categoria");

        txtCategoriaRegistros.setEditable(false);

        txtDescripcionRegistros.setEditable(false);
        txtDescripcionRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionRegistrosActionPerformed(evt);
            }
        });

        txtEanRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanRegistrosActionPerformed(evt);
            }
        });

        lblModuloRegistros.setText("MODULO REGISTROS");

        javax.swing.GroupLayout pnlRegistrosLayout = new javax.swing.GroupLayout(pnlRegistros);
        pnlRegistros.setLayout(pnlRegistrosLayout);
        pnlRegistrosLayout.setHorizontalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoRegistros)
                            .addComponent(lblEanRegistros))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEanRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblDescripcionRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcionRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblFechaIngresoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblCantidadRegistros)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(lblCategoriaRegistros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCategoriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrosLayout.createSequentialGroup()
                                .addComponent(btnOkRegistros)
                                .addGap(20, 20, 20))
                            .addComponent(btnCancelarRegistros, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblModuloRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        pnlRegistrosLayout.setVerticalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(btnOkRegistros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarRegistros)
                            .addComponent(txtCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoRegistros)
                            .addComponent(lblDescripcionRegistros)
                            .addComponent(lblCategoriaRegistros)
                            .addComponent(txtCategoriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEanRegistros)
                                .addComponent(txtEanRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCantidadRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaIngresoRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModuloRegistros)
                .addGap(11, 11, 11))
        );

        jtpInventario.addTab("tab2", pnlRegistros);

        lblCodigoActualizar.setText("Codigo");

        lblDescripcionActualizar.setText("Descripcion");

        lblEanActualizar.setText("Ean");

        lblCategoriaActualizar.setText("Categoria");

        lblCantidadActualActualizar.setText("Cantidad Actual");

        lblCantidadReconteoActualizar.setText("Cantidad Reconteo");

        btnGuardarActualizar.setText("Guardar");
        btnGuardarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActualizarActionPerformed(evt);
            }
        });

        jtActualizar.setForeground(new java.awt.Color(0, 204, 204));
        jtActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EAN", "CODIGO", "DESCRIPCION", "FECHA ", "CANTIDAD ACTUAL", "RECONTEO"
            }
        ));
        jScrollPane2.setViewportView(jtActualizar);

        btnBuscarActualizar.setBorder(null);
        btnBuscarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActualizarActionPerformed(evt);
            }
        });

        btnModificarActualizar.setText("Modificar");
        btnModificarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActualizarActionPerformed(evt);
            }
        });

        btnCancelarActualizar.setText("Cancelar");
        btnCancelarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarActionPerformed(evt);
            }
        });

        txtCodigoActualizar1.setEditable(false);

        txtCodigoActualizar5.setEditable(false);

        lblModuloRegistros1.setText("Modulo Registros");

        lblModuloRegistros2.setText("Modulo Registros");

        lblModuloActualizar.setText("MODULO ACTUALIZAR");

        javax.swing.GroupLayout pnlActualizarLayout = new javax.swing.GroupLayout(pnlActualizar);
        pnlActualizar.setLayout(pnlActualizarLayout);
        pnlActualizarLayout.setHorizontalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblEanActualizar)
                                .addGap(24, 24, 24)
                                .addComponent(txtCodigoActualizar))
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblCodigoActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addComponent(lblDescripcionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addComponent(txtCodigoActualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblCategoriaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarActualizar)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                                .addComponent(lblCantidadActualActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCantidadReconteoActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoActualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnGuardarActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarActualizar)
                                .addGap(10, 10, 10))))
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addComponent(lblModuloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlActualizarLayout.createSequentialGroup()
                    .addGap(338, 338, 338)
                    .addComponent(lblModuloRegistros1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(341, Short.MAX_VALUE)))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                    .addContainerGap(350, Short.MAX_VALUE)
                    .addComponent(lblModuloRegistros2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(329, 329, 329)))
        );
        pnlActualizarLayout.setVerticalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoActualizar)
                        .addComponent(lblCategoriaActualizar)
                        .addComponent(lblDescripcionActualizar)
                        .addComponent(btnModificarActualizar)
                        .addComponent(txtCodigoActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoActualizar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEanActualizar)
                    .addComponent(lblCantidadActualActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCantidadReconteoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarActualizar)
                    .addComponent(btnCancelarActualizar)
                    .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoActualizar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoActualizar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModuloActualizar)
                .addGap(50, 50, 50))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlActualizarLayout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(lblModuloRegistros1)
                    .addContainerGap(205, Short.MAX_VALUE)))
            .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                    .addContainerGap(215, Short.MAX_VALUE)
                    .addComponent(lblModuloRegistros2)
                    .addGap(205, 205, 205)))
        );

        jtpInventario.addTab("tab3", pnlActualizar);

        bckModuloInv.add(jtpInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 820, 440));

        lblNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 51, 255));
        lblNombreUsuario.setText("BIENVENIDO USUARIO JCPALMER");
        bckModuloInv.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckModuloInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bckModuloInv, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnOkConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkConsultarActionPerformed

    private void btnOkRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkRegistrosActionPerformed

    private void txtDescripcionRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionRegistrosActionPerformed

    private void txtEanRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanRegistrosActionPerformed

    private void btnGuardarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActualizarActionPerformed

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    private void btnModificarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActualizarActionPerformed

    private void btnCancelarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bckModuloInv;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JButton btnCancelarActualizar;
    private javax.swing.JButton btnCancelarConsultar;
    private javax.swing.JButton btnCancelarRegistros;
    private javax.swing.JButton btnGuardarActualizar;
    private javax.swing.JButton btnModificarActualizar;
    private javax.swing.JButton btnOkConsultar;
    private javax.swing.JButton btnOkRegistros;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtActualizar;
    private javax.swing.JTable jtConsultar;
    private javax.swing.JTable jtRegistros;
    private javax.swing.JTabbedPane jtpInventario;
    private javax.swing.JLabel lblBuscarPorConsultar;
    private javax.swing.JLabel lblCantidadActualActualizar;
    private javax.swing.JLabel lblCantidadReconteoActualizar;
    private javax.swing.JLabel lblCantidadRegistros;
    private javax.swing.JLabel lblCategoriaActualizar;
    private javax.swing.JLabel lblCategoriaRegistros;
    private javax.swing.JLabel lblCodigoActualizar;
    private javax.swing.JLabel lblCodigoRegistros;
    private javax.swing.JLabel lblDescripcionActualizar;
    private javax.swing.JLabel lblDescripcionRegistros;
    private javax.swing.JLabel lblEanActualizar;
    private javax.swing.JLabel lblEanConsultar;
    private javax.swing.JLabel lblEanRegistros;
    private javax.swing.JLabel lblFechaFinConsultar;
    private javax.swing.JLabel lblFechaIngresoRegistros;
    private javax.swing.JLabel lblFechaInicioConsultar;
    private javax.swing.JLabel lblLogoEcuaStock;
    private javax.swing.JLabel lblModuloActualizar;
    private javax.swing.JLabel lblModuloConsultar;
    private javax.swing.JLabel lblModuloRegistros;
    private javax.swing.JLabel lblModuloRegistros1;
    private javax.swing.JLabel lblModuloRegistros2;
    private javax.swing.JLabel lblNombreSucursal;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlActualizar;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlRegistros;
    private javax.swing.JTextField txtCantidadRegistros;
    private javax.swing.JTextField txtCategoriaRegistros;
    private javax.swing.JTextField txtCodigoActualizar;
    private javax.swing.JTextField txtCodigoActualizar1;
    private javax.swing.JTextField txtCodigoActualizar2;
    private javax.swing.JTextField txtCodigoActualizar3;
    private javax.swing.JTextField txtCodigoActualizar4;
    private javax.swing.JTextField txtCodigoActualizar5;
    private javax.swing.JTextField txtCodigoRegistros;
    private javax.swing.JTextField txtDescripcionRegistros;
    private javax.swing.JTextField txtEanRegistros;
    // End of variables declaration//GEN-END:variables
}
